name: Update Test262

on:
  push:
    branches:
      - master
      - wpedantic-compat

jobs:
  update-test262:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone test262 repo
        run: git clone https://github.com/tc39/test262.git test262

      - name: Run make test2-update
        run: make test2-update
        
      - name: Check for changes in test262_errors.txt
        if: ${{ github.ref }} == 'refs/heads/wpedantic-compat'
        run: |
          git diff --quiet
        
      - name: Commit any changes in test262_errors.txt
        if: ${{ github.ref }} == 'refs/heads/master'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git diff --quiet || (git add test262_errors.txt && git commit -m "Updated test262_errors.txt")
          git push
